### ISSUE TITLE
Minor Contamination Plots (Duplex and Unfiltered)

### ISSUE THREAD

**Issue by rhshah** [msk-access/biometrics#9]
* biometrics version: 0.1.12
* Python version: 
* Operating System:

### Description

When only couple of sites are contributing to noise, For the example below from @andurill  the samples are in the same order on the X-axis. And the high maf at 22:21135763 is due to sub-optimal alignment of the reads at a repetitive region.

#### Site with Alignment issue
<img width="615" alt="Screen Shot 2021-01-13 at 11 48 01 PM" src="https://user-images.githubusercontent.com/1289674/104616627-83022a00-5658-11eb-820b-168708684093.png">

#### Current plot
<img width="827" alt="current_version" src="https://user-images.githubusercontent.com/1289674/104616629-839ac080-5658-11eb-97d6-bcc483e344d3.png">

#### Proposed Version 
![Screen Shot 2021-01-14 at 11 07 40 AM](https://user-images.githubusercontent.com/1289674/104617032-f86dfa80-5658-11eb-9cae-c5b43d1141a6.png)

**Comment by murphycj2** [comment]
#15
